import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "components/Navbar";
import Hero from "components/Hero";
import DetailsSection from "components/DetailsSection";
import AntwortSection from "components/AntwortSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Anne & Fabian</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/heart.svg" />
      </Head>

      <main className="h-screen text-darkgreen">
        <Navbar />
        <Hero />
        <DetailsSection />
        <AntwortSection />
      </main>
    </>
  );
}
